/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as MinhaContaPedidosRouteImport } from './routes/minha-conta/pedidos'
import { Route as PedidoFalhaRouteImport } from './routes/pedido/falha'
import { Route as PedidoPendenteRouteImport } from './routes/pedido/pendente'
import { Route as PedidoSucessoRouteImport } from './routes/pedido/sucesso'
import { Route as ProdutosSlugRouteImport } from './routes/produtos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaPedidosRoute = MinhaContaPedidosRouteImport.update({
  id: '/minha-conta/pedidos',
  path: '/minha-conta/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoFalhaRoute = PedidoFalhaRouteImport.update({
  id: '/pedido/falha',
  path: '/pedido/falha',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoPendenteRoute = PedidoPendenteRouteImport.update({
  id: '/pedido/pendente',
  path: '/pedido/pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoSucessoRoute = PedidoSucessoRouteImport.update({
  id: '/pedido/sucesso',
  path: '/pedido/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosSlugRoute = ProdutosSlugRouteImport.update({
  id: '/produtos/$slug',
  path: '/produtos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/minha-conta/pedidos': typeof MinhaContaPedidosRoute
  '/pedido/falha': typeof PedidoFalhaRoute
  '/pedido/pendente': typeof PedidoPendenteRoute
  '/pedido/sucesso': typeof PedidoSucessoRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/minha-conta/pedidos': typeof MinhaContaPedidosRoute
  '/pedido/falha': typeof PedidoFalhaRoute
  '/pedido/pendente': typeof PedidoPendenteRoute
  '/pedido/sucesso': typeof PedidoSucessoRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/minha-conta/pedidos': typeof MinhaContaPedidosRoute
  '/pedido/falha': typeof PedidoFalhaRoute
  '/pedido/pendente': typeof PedidoPendenteRoute
  '/pedido/sucesso': typeof PedidoSucessoRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogo'
    | '/checkout'
    | '/contato'
    | '/minha-conta/pedidos'
    | '/pedido/falha'
    | '/pedido/pendente'
    | '/pedido/sucesso'
    | '/produtos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/checkout'
    | '/contato'
    | '/minha-conta/pedidos'
    | '/pedido/falha'
    | '/pedido/pendente'
    | '/pedido/sucesso'
    | '/produtos/$slug'
  id:
    | '__root__'
    | '/'
    | '/catalogo'
    | '/checkout'
    | '/contato'
    | '/minha-conta/pedidos'
    | '/pedido/falha'
    | '/pedido/pendente'
    | '/pedido/sucesso'
    | '/produtos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRoute
  CheckoutRoute: typeof CheckoutRoute
  ContatoRoute: typeof ContatoRoute
  MinhaContaPedidosRoute: typeof MinhaContaPedidosRoute
  PedidoFalhaRoute: typeof PedidoFalhaRoute
  PedidoPendenteRoute: typeof PedidoPendenteRoute
  PedidoSucessoRoute: typeof PedidoSucessoRoute
  ProdutosSlugRoute: typeof ProdutosSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta/pedidos': {
      id: '/minha-conta/pedidos'
      path: '/minha-conta/pedidos'
      fullPath: '/minha-conta/pedidos'
      preLoaderRoute: typeof MinhaContaPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/falha': {
      id: '/pedido/falha'
      path: '/pedido/falha'
      fullPath: '/pedido/falha'
      preLoaderRoute: typeof PedidoFalhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/pendente': {
      id: '/pedido/pendente'
      path: '/pedido/pendente'
      fullPath: '/pedido/pendente'
      preLoaderRoute: typeof PedidoPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/sucesso': {
      id: '/pedido/sucesso'
      path: '/pedido/sucesso'
      fullPath: '/pedido/sucesso'
      preLoaderRoute: typeof PedidoSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/$slug': {
      id: '/produtos/$slug'
      path: '/produtos/$slug'
      fullPath: '/produtos/$slug'
      preLoaderRoute: typeof ProdutosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRoute,
  CheckoutRoute: CheckoutRoute,
  ContatoRoute: ContatoRoute,
  MinhaContaPedidosRoute: MinhaContaPedidosRoute,
  PedidoFalhaRoute: PedidoFalhaRoute,
  PedidoPendenteRoute: PedidoPendenteRoute,
  PedidoSucessoRoute: PedidoSucessoRoute,
  ProdutosSlugRoute: ProdutosSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
